name: telegram message
on: [push]

jobs:
  build:
    name: Push notification
    runs-on: ubuntu-latest
    steps:
      - name: send custom message with args
        uses: actions/checkout@master
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          # disable_web_page_preview: true
